/**
 * API v1
 * FormAPI is a service that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient', '../model/SubmissionDataBatchRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SubmissionDataBatchRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.FormAPI) {
      root.FormAPI = {};
    }
    root.FormAPI.SubmissionBatchData = factory(root.FormAPI.ApiClient, root.FormAPI.SubmissionDataBatchRequest);
  }
}(this, function(ApiClient, SubmissionDataBatchRequest) {
  'use strict';




  /**
   * The SubmissionBatchData model module.
   * @module model/SubmissionBatchData
   * @version 2.8.0
   */

  /**
   * Constructs a new <code>SubmissionBatchData</code>.
   * @alias module:model/SubmissionBatchData
   * @class
   * @param submissions {Array.<module:model/SubmissionDataBatchRequest>} 
   */
  var exports = function(submissions) {
    var _this = this;




    _this['submissions'] = submissions;
  };

  /**
   * Constructs a <code>SubmissionBatchData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SubmissionBatchData} obj Optional instance to populate.
   * @return {module:model/SubmissionBatchData} The populated <code>SubmissionBatchData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('metadata')) {
        obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
      }
      if (data.hasOwnProperty('test')) {
        obj['test'] = ApiClient.convertToType(data['test'], 'Boolean');
      }
      if (data.hasOwnProperty('template_id')) {
        obj['template_id'] = ApiClient.convertToType(data['template_id'], 'String');
      }
      if (data.hasOwnProperty('submissions')) {
        obj['submissions'] = ApiClient.convertToType(data['submissions'], [SubmissionDataBatchRequest]);
      }
    }
    return obj;
  }

  /**
   * @member {Object} metadata
   */
  exports.prototype['metadata'] = undefined;
  /**
   * @member {Boolean} test
   */
  exports.prototype['test'] = undefined;
  /**
   * @member {String} template_id
   */
  exports.prototype['template_id'] = undefined;
  /**
   * @member {Array.<module:model/SubmissionDataBatchRequest>} submissions
   */
  exports.prototype['submissions'] = undefined;



  return exports;
}));


