/**
 * API v1
 * FormAPI is a service that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient', '../model/Templatesv2TemplateDocumentMetadata'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Templatesv2TemplateDocumentMetadata'));
  } else {
    // Browser globals (root is window)
    if (!root.FormAPI) {
      root.FormAPI = {};
    }
    root.FormAPI.Templatesv2TemplateDocument = factory(root.FormAPI.ApiClient, root.FormAPI.Templatesv2TemplateDocumentMetadata);
  }
}(this, function(ApiClient, Templatesv2TemplateDocumentMetadata) {
  'use strict';




  /**
   * The Templatesv2TemplateDocument model module.
   * @module model/Templatesv2TemplateDocument
   * @version 2.14.0
   */

  /**
   * Constructs a new <code>Templatesv2TemplateDocument</code>.
   * @alias module:model/Templatesv2TemplateDocument
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>Templatesv2TemplateDocument</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Templatesv2TemplateDocument} obj Optional instance to populate.
   * @return {module:model/Templatesv2TemplateDocument} The populated <code>Templatesv2TemplateDocument</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('metadata')) {
        obj['metadata'] = Templatesv2TemplateDocumentMetadata.constructFromObject(data['metadata']);
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('storage')) {
        obj['storage'] = ApiClient.convertToType(data['storage'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Templatesv2TemplateDocumentMetadata} metadata
   */
  exports.prototype['metadata'] = undefined;
  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {module:model/Templatesv2TemplateDocument.StorageEnum} storage
   */
  exports.prototype['storage'] = undefined;


  /**
   * Allowed values for the <code>storage</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StorageEnum = {
    /**
     * value: "cache"
     * @const
     */
    "cache": "cache"  };


  return exports;
}));


